# Generated by Django 2.1.5 on 2019-01-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='runtime',
            field=models.CharField(default='00:00:00', max_length=8),
        ),
    ]
